version: '2.1'

services:
  temp-music:
    image: temp-music
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js